- name: "Build Docker images with Ansible"
  hosts: app_servers
  become: true
  vars:
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    build_number: "{{ build_number }}"  # Use the build_number variable

  tasks:
    - name: Check if repo directory exists
      stat:
        path: /home/ubuntu/to-do-app
      register: repo_stat

    - name: Clone repo if not exists
      command: git clone https://github.com/IbrahimAamer1/to-do-app.git
      args:
        chdir: /home/ubuntu
      when: not repo_stat.stat.exists
      ignore_errors: yes

    - name: Log in to Docker
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build Docker image
      command: docker build -t ibrahimaamer/to-do-app:{{"build_number"}} /home/ubuntu/to-do-app
      args:
        chdir: /home/ubuntu/to-do-app
      ignore_errors: yes
